language: ruby
sudo: false

before_script:
  - "RAILS_ENV=test bundle exec rake db:setup"

branches:
  except:
    - dont-merge/offline-scanning-without-authentication

notifications:
  slack: zeuswpi:EWgfa9aeAwSfi3mnLxw6Hi9N

  email:
    recipients:
      - gandalf@zeus.ugent.be
    on_success: never
    on_failure: change
