language: ruby
rvm:
  - 2.1.0

before_install:
  - "cd Isengard"

before_script:
  - "RAILS_ENV=test bundle exec rake db:setup"

notifications:
  email:
    recipients:
      - gandalf@zeus.ugent.be
    on_success: change
    on_failure: change

  irc: 
    channels:
      - "wina.ugent.be#hydra"
    on_success: never
    on_failure: always


