development:
  secret_key_base: a27fcd9aa2eabd14030493d6b5a1521ba09c9d23a1dd90b3c9d6914b8d226d1df8b46af3005f73a29c3ef1acd86de3669fbe08605d9ce8da73856c734f8a0e36
  fk_auth_url: https://intranet.fkgent.be/clubs
  fk_auth_salt: '#development#'
  fk_auth_key: '#development#'
  enrollment_key: '#development#'
  omniauth_client_id: 'tomtest'
  omniauth_client_secret: 'blargh'


test:
  secret_key_base: 24f28e9f092ff3849df2fcfaf5a0a56a18f098f314a369ea619171a0d47eaea9f0458c25572c52b4cc8c4823d75e2ea5f6477dfcc1e7b5ea46d4ca2be22cfb84
  fk_auth_url: https://intranet.fkgent.be/clubs
  fk_auth_salt: '#development#'
  fk_auth_key: '#development#'
  enrollment_key: '#development#'

production:
  secret_key_base: a27fcd9aa2eabd14030493d6b5a1521ba09c9d23a1dd90b3c9d6914b8d226d1df8b46af3005f73a29c3ef1acd86de3669fbe08605d9ce8da73856c734f8a0e36
  fk_auth_url: https://intranet.fkgent.be/clubs
  fk_auth_salt: '#development#'
  fk_auth_key: '#development#'
  enrollment_key: '#development#'
  omniauth_client_id: ''
  omniauth_client_secret: ''
